# Generated by Django 5.1.7 on 2025-04-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodBank',
            fields=[
                ('blood_group', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('units', models.IntegerField(default=0)),
            ],
        ),
    ]
