# Generated by Django 5.1.7 on 2025-04-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_bloodrequest_delete_bloodbank'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='status',
            field=models.CharField(default='Pending', max_length=10),
        ),
    ]
